[package]
name = "dyndns"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0.229", features = ["derive"] }
ipnet = "2.12.2"
axum = { version = "0.8.9" }
tower-http = { version = "0.7.1", features = ["auth", "trace"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
reqwest = { version = "0.13.5", features = ["json"] }
thiserror = "2.0.21"
axum-extra = { version = "0.12.6", features = ["typed-header"] }
