---
services:
  pdns:
    image: powerdns/pdns-auth-52
    environment:
      - PDNS_AUTH_API_KEY=secret
    cap_add:
      - net_bind_service
    ports:
      - "1053:53"
      - "1053:53/udp"
      - "8081:8081"
