#!/usr/bin/env -S ansible-playbook -i localhost, -c local
---
- hosts: localhost
  vars:
    ula_prefix: "fd00::/64"
    oneandone_prefix: "{{ athmer_home_prefix|default(hostvars['localhost'].ansible_default_ipv6.address + '/' + hostvars['localhost'].ansible_default_ipv6.prefix) | ansible.utils.ipaddr('network/prefix') }}"
    mac:
      hpe_proliant_0: 5c:ba:2c:22:c6:42
      rpi1_0: b8:27:eb:16:39:6d
      rpi1_1: b8:27:eb:db:6c:6e
      rpi0w_0: b8:27:eb:b0:b5:82
      rpi4_0: dc:a6:32:ea:1a:1f
      rpi4_1: dc:a6:32:5a:0b:84
      rpi400_0: e4:5f:01:a1:dd:f6
      rpi400w_0: e4:5f:01:a1:dd:f7
      otg_eth_0: 00:e0:4c:53:44:58
      nuc_0: 94:c6:91:a5:2d:ff
      nuc_1: 94:C6:91:A5:32:6D
      cm4_1: e4:5f:01:ec:3f:97
      cm4_2: e4:5f:01:ec:6c:1f
      cm4_6: e4:5f:01:e1:0a:c7
  tasks:
    - name: read zones
      ansible.builtin.include_vars:
        file: zones.tmpl.yaml
    - name: write generated file
      copy:
        content: "{{ zones|to_yaml }}"
        dest: ./zones.yaml
